### PR TITLE
1 create api project

### LINKED ISSUE #1: Create API Project
Initial project actions

Creation of the .NET Web Api project for backend services

`dotnet new webapi -o api`

### PR DESCRIPTION
**Pull request by mikemachacky**
#1 Create initial api project in .NET 8 web api

### CODE REVIEW

**Review by ptr47 — APPROVED** [review]
very nice 👍

**Review by ptr47 — CHANGES_REQUESTED** [review]
need to remove folders 'bin' and 'debug'

**Comment by mikemachacky** [comment]
Reuploaded api project after adding gitignore

**Review by ptr47 — APPROVED** [review]
very nice 👍

**Pull request merged**
